DECLARE
    VA_ARCHIVO_DEF UTL_FILE.FILE_TYPE;
    NOMBRE_ARCHIVO NVARCHAR2(100) := 'Prueba.txt';
BEGIN
    VA_ARCHIVO_DEF := UTL_FILE.FOPEN('BRAYMON_HOME_DIRECTORY',NOMBRE_ARCHIVO,'W');
    IF UTL_FILE.IS_OPEN(VA_ARCHIVO_DEF) THEN
        DBMS_OUTPUT.PUT_LINE('Archivo creado satisfactoriamente: ' || NOMBRE_ARCHIVO);
    ELSE
        DBMS_OUTPUT.PUT_LINE('EL archivo no se pudo crear: ' || NOMBRE_ARCHIVO);
    END IF;

    UTL_FILE.PUT_LINE(VA_ARCHIVO_DEF,'Hola Mundo');
    UTL_FILE.FFLUSH(VA_ARCHIVO_DEF);
    UTL_FILE.FCLOSE(VA_ARCHIVO_DEF);
END;
