DECLARE
    L_PROG_SHORT_NAME VARCHAR2(240);
    L_EXEC_SHORT_NAME VARCHAR2(240);
    L_APPL_FULL_NAME  VARCHAR2(240) := 'Application Object Library';
    L_APPL_SHORT_NAME VARCHAR2(240);
    L_DEL_PROG_FLAG   VARCHAR2(1) := 'Y';
    L_DEL_EXEC_FLAG   VARCHAR2(1) := 'Y';
BEGIN
    L_PROG_SHORT_NAME := 'HCS_CARMONA_HIWORLD';
    L_EXEC_SHORT_NAME := 'HCS_CARMONA_HIWORLD';
    L_APPL_SHORT_NAME := 'FND';
    
    IF
        L_DEL_PROG_FLAG = 'Y'
        AND FND_PROGRAM.PROGRAM_EXISTS(L_PROG_SHORT_NAME,L_APPL_SHORT_NAME)
    THEN
        FND_PROGRAM.DELETE_PROGRAM(L_PROG_SHORT_NAME,L_APPL_FULL_NAME);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('BORRADO EL PROGRAMA CONCURRENTE: ' || L_PROG_SHORT_NAME);
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO EXISTE PROGRAMA: ' || L_PROG_SHORT_NAME);
    END IF;

    IF
        L_DEL_EXEC_FLAG = 'Y'
        AND FND_PROGRAM.EXECUTABLE_EXISTS(L_EXEC_SHORT_NAME,L_APPL_SHORT_NAME)
    THEN
        FND_PROGRAM.DELETE_EXECUTABLE(L_EXEC_SHORT_NAME,L_APPL_FULL_NAME);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('BORRADO EL EXECUTABLE: ' || L_EXEC_SHORT_NAME);
    ELSE
        DBMS_OUTPUT.PUT_LINE('EXISTE EXECUTABLE: ' || L_EXEC_SHORT_NAME);
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR AL ELIMINAR: ' || SQLERRM);
END;
