BEGIN
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SQLTERMINATOR',TRUE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',TRUE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'TABLESPACE',FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'CONSTRAINTS_AS_ALTER',FALSE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'OID',TRUE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SIZE_BYTE_KEYWORD',TRUE);
    DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'EMIT_SCHEMA',FALSE);
END;

--
SELECT
    TABLE_NAME
   ,REPLACE(DBMS_METADATA.GET_DDL('TABLE',TABLE_NAME,OWNER)
            ,'"') AS DMML
FROM
    ALL_TABLES
WHERE
        OWNER = 'APPS'
    AND TABLE_NAME IN ( 'XXBM_SUPPLIERS','XXBM_SUPPLIERS_INT','XXBM_SUPPLIERS_ADDRESSES','XXBM_SUPPLIERS_ADDRESSES_INT');

--
SELECT
    VIEW_NAME
   ,REPLACE(DBMS_METADATA.GET_DDL('VIEW',VIEW_NAME,OWNER),'"') AS DMML
FROM
    ALL_VIEWS
WHERE
        OWNER = 'APPS'
    AND VIEW_NAME IN ( 'XXBM_SUPPLIERS_V', 'XXBM_SUPPLIERS_ADDRESSES_V');